language: go
go:
  - 1.x

service:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple-go-travis .
  - docker tag simple-go-travis aluminetchidiebre/simple-go-travis:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push aluminetchidiebre/simple-go-travis
