language: go
go:
  - 1.x

service:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - go test -v

script:
  - docker --version # print the version for logging
  - docker build -t simple-go-travis .
  - docker tag simple-go-travis aluminetchidiebre/simple-go-travis:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #we pipe the env variable $DOCKER_PASSWORD into the next docker login command so the password will not be really printed out in the logs. We don't want secrets to be printed on logs :)
  - docker push aluminetchidiebre/simple-go-travis
